baseURL = "https://aacs2020.github.io/"
#languageCode = "en-us"
languageCode = "zh-CN"
title = "AACS | 澳洲华人学者协会"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "关于我们"
url     = "about"
weight  = 2
[[menu.main]]
name    = "协会项目孵化中心"
# url     = "projects"
url     = "service"
weight  = 3
[[menu.main]]
name    = "协会活动"
# url     = "activities"
url     = "blog"
weight  = 4
[[menu.main]]
name    = "协会成员留言"
# url     = "bbs"
url     = "gallery"
weight  = 5
[[menu.main]]
name    = "新闻板块"
url     = "news"
weight  = 6
[[menu.main]]
name    = "协会发展路线"
# url     = "future"
url     = "contact"
weight  = 7

# Site Params
[params]
home = "首页"
logo = "images/logo.jpg"
dateFormat = "1 January 2020"
# Meta data
description = "AACS homepage"
author = "AACS"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "澳洲华人学者协会(AACS)"
description = "协会旨在促进澳大利亚华人学者群体的沟通、交流与互助"
# button
btn     = true
btnText = "点击查看更多"
btnURL  = "/about"

# flip text
[[params.banner.flipText]]
title   = "协会公众号: AACS华人学者"
[[params.banner.flipText]]
title   = "协会微博: 澳洲华人学者AACS"
[[params.banner.flipText]]
title   = "协会知乎: 澳洲华人学者AACS"

# Homepage About Section
[params.about]
enable  = true
title   = "简介"
content = "澳洲华人学者协会于2020年3月20日成立，是在澳大利亚悉尼注册的非盈利性组织，是一个澳洲华人学者相互交流学术经验与分享资源的平台。已有百余澳洲学者入驻协会，包括计算机，工程，生物，医学，教育等专业的澳洲大学教授(包括澳洲八大)澳洲博士及博士后 。"
image   = "images/aacs/aacs-logo.png"

# Call to Action
[params.cta]
enable  = true
title   = "XXXX XXXX XX？"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact"
btnURL  = "/about"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "近期活动"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"


# hugo low-level config
[markup.goldmark.renderer]
unsafe=true